routes/admin.php
<?php


use App\Http\Controllers\DashboardController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('dashboard', DashboardController::class)->name('dashboard');

Route::prefix('userManagement')->as('userManagement.')->group(function (){
   Route::resource('role', RoleController::class);
   Route::resource('user', UserController::class);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware([
    'auth:sanctum','checkRoleMiddleware',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
    use HasFactory, SoftDeletes;

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    protected $fillable = [
        'title',
        'type'
    ];

    public function permissions(): BelongsToMany
    {
       return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Role\StoreRoleRequest;
use App\Http\Requests\Role\UpdateRoleRequest;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class RoleController extends Controller
{

    public function index()
    {
        abort_if(Gate::denies('role_access'),
        403,
        'you are not able to access this resource');

        $roles=Role::all();
        return view('admin.user_management.role.index', compact('roles'));
    }

    public function create()
    {
        abort_if(Gate::denies('role_create'),
        403,
        'you are not able to access this resource');

        $permissions=Permission::all();
        return view('admin.user_management.role.create',compact('permissions'));
    }

    public function store(StoreRoleRequest $request)
    {
        Role::create($request->validated());

        toast('Role Added Successfully', 'success');
        return back();
    }


    public function show(Role $role)
    {
        //
    }

    public function edit(Role $role)
    {
        abort_if(Gate::denies('role_create'),
            403,
            'you are not able to access this resource');
        $permissions=Permission::all();
        return view('admin.user_management.role.edit',compact('role','permissions'));
    }

    public function update(UpdateRoleRequest $request, Role $role)
    {
        abort_if(Gate::denies('role_edit'),
        403,
        'you are not able to access this resource');

        $role->update($request->validated());

        toast('Role Edited Successfully', 'success');
        return redirect(route('admin.userManagement.role.index'));
    }

    public function destroy(Role $role)
    {
        $role->delete();

        toast('Role Deleted Successfully','success');
        return back();
    }
}

resources/views/admin/user_management/role/create.blade.php
@extends('admin.layouts.master')
{{--    <div class="row">--}}
{{--        <div class="col-md-12 mb-2">--}}
{{--            <div class="card">--}}
{{--                <div class="col-lg-12 grid-margin stretch-card">--}}
{{--                    <div class="card">--}}
{{--                        <div class="card-body">--}}
{{--                            <div class="d-flex justify-content-between">--}}
{{--                                <h4 class="card-title">Role</h4>--}}
{{--                                @can('role_create')--}}
{{--                                    <a href="{{route('admin.userManagement.role.create')}}" class="btn btn-md btn-rounded btn-outline-info">--}}
{{--                                        <i class="fa fa-plus-circle"></i>  Add New--}}
{{--                                    </a>--}}
{{--                                @endcan--}}
{{--                            </div>--}}
{{--                <div class="card-body">--}}
{{--                    <form action="{{route('admin.userManagement.role.store')}}" method="post">--}}
{{--                        @csrf--}}
{{--                        <div class="row">--}}
{{--                            <div class="col-md-12 mb-2">--}}
{{--                                <label for="title" class="form-label">Title *</label>--}}
{{--                                <input type="text"--}}
{{--                                       name="title"--}}
{{--                                       class="form-control @error('title') is-invalid @enderror"--}}
{{--                                       id="title"--}}
{{--                                       value="{{old('title')}}"--}}
{{--                                       placeholder="enter title"--}}
{{--                                >--}}
{{--                                @error('title')--}}
{{--                                <div class="invalid-feedback">{{$message}}</div>--}}
{{--                                @enderror--}}
{{--                            </div>--}}

{{--                            <div class="col-md-12 mb-3">--}}
{{--                                <label for="permissions" class="form-label">Permissions *</label>--}}
{{--                                <fieldset>--}}
{{--                                    <div class="row">--}}
{{--                                        @foreach($permissions as $permission)--}}
{{--                                            <div class="col-sm-3">--}}
{{--                                                <div class="form-check form-check-flat form-check-primary">--}}
{{--                                                    <label class="form-check-label">--}}
{{--                                                        <input type="checkbox" name="permissions[]"--}}
{{--                                                               value="{{$permission->id}}" class="form-check-input">--}}
{{--                                                        {{$permission->title}}--}}
{{--                                                    </label>--}}
{{--                                                </div>--}}
{{--                                            </div>--}}
{{--                                        @endforeach--}}
{{--                                    </div>--}}
{{--                                </fieldset>--}}
{{--                                @error('permissions')--}}
{{--                                <p class="text-danger">{{$message}}</p>--}}
{{--                                @enderror--}}
{{--                                @error('permissions.*')--}}
{{--                                <p class="text-danger">{{$message}}</p>--}}
{{--                                @enderror--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <button type="submit" class="btn btn-primary">--}}
{{--                            Save--}}
{{--                        </button>--}}
{{--                    </form>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}


@section('content')
    <div class="row mb-3">
        <div class="col-12">
            <div class="d-flex justify-content-between">
                <div>
                    Home/ UserManagement
                </div>
                <div class="active">Role</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title">Role</h4>
                    @can('role_access')
                        <a href="{{route('admin.userManagement.role.index')}}"
                           class="btn btn-md btn-rounded btn-outline-info">
                            <i class="fa fa-plus-circle"></i> Role List
                        </a>
                    @endcan
                </div>
                <form action="{{route('admin.userManagement.role.store')}}" method="post">
                    @csrf
                    <div class="row m-1">
                        <label for="title" class="form-label">Title *</label>
                        <input
                            type="text"
                            name="title"
                            id="title"
                            value="{{old('title')}}"
                            class="form-control @error('title') is-invalid @enderror"
                            placeholder="Title"
                            aria-label="Username">
                        @error('title')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                    <label for="permissions" class="form-label">Permissions *</label>
                    <div class="row">
                        @foreach($permissions as $permission)
                            <div class="col-sm-3 mb-1">
                                <div class="form-check form-check-flat form-check-primary">
                                    <label class="form-check-label">
                                        <input type="checkbox" name="permissions[]"
                                               value="{{$permission->id}}" class="form-check-input">
                                        {{$permission->title}}
                                    </label>
                                </div>
                            </div>
                        @endforeach
                        @error('permissions')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                        @error('permissions.*')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user_management/role/edit.blade.php
@extends('admin.layouts.master')
{{--    <div class="row">--}}
{{--        <div class="col-md-12 mb-2">--}}
{{--            <div class="card">--}}
{{--                <div class="col-lg-12 grid-margin stretch-card">--}}
{{--                    <div class="card">--}}
{{--                        <div class="card-body">--}}
{{--                            <div class="d-flex justify-content-between">--}}
{{--                                <h4 class="card-title">Role</h4>--}}
{{--                                @can('role_create')--}}
{{--                                    <a href="{{route('admin.userManagement.role.create')}}" class="btn btn-md btn-rounded btn-outline-info">--}}
{{--                                        <i class="fa fa-plus-circle"></i>  Add New--}}
{{--                                    </a>--}}
{{--                                @endcan--}}
{{--                            </div>--}}
{{--                <div class="card-body">--}}
{{--                    <form action="{{route('admin.userManagement.role.store')}}" method="post">--}}
{{--                        @csrf--}}
{{--                        <div class="row">--}}
{{--                            <div class="col-md-12 mb-2">--}}
{{--                                <label for="title" class="form-label">Title *</label>--}}
{{--                                <input type="text"--}}
{{--                                       name="title"--}}
{{--                                       class="form-control @error('title') is-invalid @enderror"--}}
{{--                                       id="title"--}}
{{--                                       value="{{old('title')}}"--}}
{{--                                       placeholder="enter title"--}}
{{--                                >--}}
{{--                                @error('title')--}}
{{--                                <div class="invalid-feedback">{{$message}}</div>--}}
{{--                                @enderror--}}
{{--                            </div>--}}

{{--                            <div class="col-md-12 mb-3">--}}
{{--                                <label for="permissions" class="form-label">Permissions *</label>--}}
{{--                                <fieldset>--}}
{{--                                    <div class="row">--}}
{{--                                        @foreach($permissions as $permission)--}}
{{--                                            <div class="col-sm-3">--}}
{{--                                                <div class="form-check form-check-flat form-check-primary">--}}
{{--                                                    <label class="form-check-label">--}}
{{--                                                        <input type="checkbox" name="permissions[]"--}}
{{--                                                               value="{{$permission->id}}" class="form-check-input">--}}
{{--                                                        {{$permission->title}}--}}
{{--                                                    </label>--}}
{{--                                                </div>--}}
{{--                                            </div>--}}
{{--                                        @endforeach--}}
{{--                                    </div>--}}
{{--                                </fieldset>--}}
{{--                                @error('permissions')--}}
{{--                                <p class="text-danger">{{$message}}</p>--}}
{{--                                @enderror--}}
{{--                                @error('permissions.*')--}}
{{--                                <p class="text-danger">{{$message}}</p>--}}
{{--                                @enderror--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <button type="submit" class="btn btn-primary">--}}
{{--                            Save--}}
{{--                        </button>--}}
{{--                    </form>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}


@section('content')
    <div class="row mb-3">
        <div class="col-12">
            <div class="d-flex justify-content-between">
                <div>
                    Home/ UserManagement
                </div>
                <div class="active">Role</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title">Role</h4>
                    @can('role_access')
                        <a href="{{route('admin.userManagement.role.index')}}"
                           class="btn btn-md btn-rounded btn-outline-info">
                            <i class="fa fa-plus-circle"></i> Role List
                        </a>
                    @endcan
                </div>
                <form action="{{route('admin.userManagement.role.update',$role)}}" method="post">
                    @csrf
                    @method('put')
                    <div class="row m-1">
                        <label for="title" class="form-label">Title *</label>
                        <input
                            type="text"
                            name="title"
                            id="title"
                            value="{{old('title',$role->title)}}"
                            class="form-control @error('title') is-invalid @enderror"
                            placeholder="Title"
                            aria-label="Username">
                        @error('title')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                    <label for="permissions" class="form-label">Permissions *</label>
                    <div class="row">
                        @foreach($permissions as $permission)
                            <div class="col-sm-3 mb-1">
                                <div class="form-check form-check-flat form-check-primary">
                                    <label class="form-check-label">
                                        <input type="checkbox" name="permissions[]"
                                               value="{{$permission->id}}"
                                               {{in_array($permission->id,$role->permissions->pluck('id')->toArray()) ? 'checked' : ''}}
                                               class="form-check-input">
                                        {{$permission->title}}
                                    </label>
                                </div>
                            </div>
                        @endforeach
                        @error('permissions')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                        @error('permissions.*')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user_management/role/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="row mb-3">
        <div class="col-12">
            <div class="d-flex justify-content-between">
                <div>
                    Home/ UserManagement
                </div>
               <div class="active">Role</div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title">Role</h4>
                    @can('role_create')
                    <a href="{{route('admin.userManagement.role.create')}}" class="btn btn-md btn-rounded btn-outline-info">
                        <i class="fa fa-plus-circle"></i>  Add New
                    </a>
                    @endcan
                </div>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>SN</th>
                            <th>Title</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($roles as $role)
                        <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$role->title}}</td>
                                <td class="d-flex m-1 p-1">
                                    @can('role_edit')
                                        <a href="{{route('admin.userManagement.role.edit', $role)}}"
                                           class="btn btn-xs btn-sm btn-outline-primary">
                                            <i class="fa fa-pencil-square"></i> edit
                                        </a>
                                    @endcan
                                    @can('role_delete')
                                        <form action="{{route('admin.userManagement.role.destroy', $role)}}"
                                              method="post" onsubmit="return confirm('Are you sure to Delete?')">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-xs btn-sm btn-outline-danger show_confirm">
                                                <i class="fa fa-trash"></i> delete
                                            </button>
                                        </form>
                                    @endcan
                                </td>
                            @empty
                            <td class="text-center" colspan="3">No Data Found</td>
                        </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection