routes/admin.php
<?php


use App\Http\Controllers\DashboardController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('dashboard', DashboardController::class)->name('dashboard');

Route::prefix('userManagement')->as('userManagement.')->group(function (){
   Route::resource('role', RoleController::class);
   Route::resource('user', UserController::class);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware([
    'auth:sanctum','checkRoleMiddleware',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Jetstream\HasTeams;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasTeams;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string<int, string>
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array<int, string>
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function role(): BelongsTo
    {
        return $this->belongsTo(Role::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class UserController extends Controller
{

    public function index()
    {
        abort_if(Gate::denies('user_access'),
        403,
        'you are not able to access this resource');

        $users=User::with('role')->whereNot('id', auth()->id())->get();
        return view('admin.user_management.user.index', compact('users'));
    }

    public function create()
    {
        abort_if(Gate::denies('user_create'),
        403,
        'you are not able to access this resource');

        $roles=Role::all();

        return view('admin.user_management.user.create', compact('roles'));
    }

    public function store(StoreUserRequest $request)
    {
        abort_if(Gate::denies('user_create'),
            403,
            'you are not able to access this resource');
        User::create($request->validated());

        toast('Users Added Successfully', 'success');
        return back();
    }


    public function show(User $user)
    {
        //
    }

    public function edit(User $user)
    {
        abort_if(Gate::denies('user_edit'),
            403,
            'you are not able to access this resource');
        $roles=Role::all();
        return view('admin.user_management.user.edit', compact('user','roles'));
    }

    public function update(Request $request, User $user)
    {
        abort_if(Gate::denies('user_edit'),
            403,
            'you are not able to access this resource');

        $user->update($request->validated());

        toast('User Updated Successfully', 'success');
        return redirect(route('admin.userManagement.user.index'));
    }

    public function destroy(User $user)
    {
        abort_if(Gate::denies('user_delete'),
            403,
            'you are not able to access this resource');

        $user->delete();

        toast('User Deleted Successfully', 'danger');
        return back();
    }
}

resources/views/admin/user_management/user/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="row mb-3">
        <div class="col-12">
            <div class="d-flex justify-content-between">
                <div>
                    Home/ UserManagement
                </div>
                <div class="active">User</div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title">User</h4>
                    @can('user_create')
                        <a href="{{route('admin.userManagement.user.create')}}" class="btn btn-md btn-rounded btn-outline-info">
                            <i class="fa fa-plus-circle"></i>  Add New
                        </a>
                    @endcan
                </div>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>SN</th>
                            <th>Title</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($users as $user)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$user->name}}</td>
                                <td class="d-flex m-1 p-1">
                                    @can('user_edit')
                                        <a href="{{route('admin.userManagement.user.edit', $user)}}"
                                           class="btn btn-xs btn-sm btn-outline-primary">
                                            <i class="fa fa-pencil-square"></i> edit
                                        </a>
                                    @endcan
                                    @can('user_delete')
                                        <form action="{{route('admin.userManagement.user.destroy', $user)}}"
                                              method="post" onsubmit="return confirm('Are you sure to Delete?')">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-xs btn-sm btn-outline-danger show_confirm">
                                                <i class="fa fa-trash"></i> delete
                                            </button>
                                        </form>
                                    @endcan
                                </td>
                                @empty
                                    <td class="text-center" colspan="3">No Data Found</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection